blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/DobroslavRadosavljevic/kuzenbo-mono/blob/main/SECURITY.md
    about: Please report security issues privately using our security policy.
  - name: Support
    url: https://github.com/DobroslavRadosavljevic/kuzenbo-mono/blob/main/SUPPORT.md
    about: Learn how to get help or ask non-security questions.
